In [6]:
import torch

print("CUDA 사용 가능?", torch.cuda.is_available())
if torch.cuda.is_available():
    print(f"GPU 이름 : {torch.cuda.get_device_name(0)}")
    print(f"GPU 개수 : {torch.cuda.device_count()}")

CUDA 사용 가능? True
GPU 이름 : NVIDIA GeForce GTX 1660 SUPER
GPU 개수 : 1


In [3]:
import torch

print(torch.tensor([1,2,3]))
print(torch.tensor([[1,2,3], [4,5,6]]))

tensor([1, 2, 3])
tensor([[1, 2, 3],
        [4, 5, 6]])


In [ ]:
import torch

tensor = torch.tensor([1,2,3])

print(tensor.dtype)
print(tensor.shape)
print(tensor.device)


torch.int64
torch.Size([3])
cpu


In [9]:
import torch

tensor = torch.tensor([1,2,3])
print(f"변환 전 : {tensor}")

tensor = tensor.reshape(3,1)
print(f"변환 후 : {tensor}")

변환 전 : tensor([1, 2, 3])
변환 후 : tensor([[1],
        [2],
        [3]])


In [1]:
import torch

tensor = torch.rand((3,3), dtype=torch.float)
print(tensor)

tensor([[0.7120, 0.5545, 0.9989],
        [0.7726, 0.1740, 0.5142],
        [0.1488, 0.0635, 0.7141]])


In [2]:
import torch

device = "cuda" if torch.cuda.is_available() else "cpu"

gpu = torch.cuda.FloatTensor([1,2,3])
tensor = torch.rand((3,3), device=device)
print(gpu)
print(tensor)

C:\Users\kimji\AppData\Local\Temp\ipykernel_26244\3882855782.py:5: UserWarning: The torch.cuda.*DtypeTensor constructors are no longer recommended. It's best to use methods such as torch.tensor(data, dtype=*, device='cuda') to create tensors. (Triggered internally at C:\actions-runner\_work\pytorch\pytorch\pytorch\torch\csrc\tensor\python_tensor.cpp:80.)
  gpu = torch.cuda.FloatTensor([1,2,3])


tensor([1., 2., 3.], device='cuda:0')
tensor([[0.0856, 0.6452, 0.7610],
        [0.0134, 0.6113, 0.9309],
        [0.5335, 0.5456, 0.7695]], device='cuda:0')


In [4]:
import torch

cpu = torch.FloatTensor([1,2,3])
gpu = cpu.cuda()
gpuTocpu = gpu.cpu()
cpuTogpu = gpuTocpu.to("cuda")

print(cpu)
print(gpu)
print(gpuTocpu)
print(cpuTogpu)

tensor([1., 2., 3.])
tensor([1., 2., 3.], device='cuda:0')
tensor([1., 2., 3.])
tensor([1., 2., 3.], device='cuda:0')


In [7]:
import torch
import numpy as np

ndarray = np.array([1,2,3], dtype=np.uint8)
print(torch.tensor(ndarray))
print(torch.Tensor(ndarray))
print(torch.from_numpy(ndarray))


tensor([1, 2, 3], dtype=torch.uint8)
tensor([1., 2., 3.])
tensor([1, 2, 3], dtype=torch.uint8)


In [9]:
import pytorch
import numpy as np

tensor = torch.cuda.FloatTensor([1,2,3])
ndarray = tensor.detach().cpu().numpy()
print(ndarray)
print(type(ndarray))


[1. 2. 3.]
<class 'numpy.ndarray'>
